{"evenements":[<!--{foreach from=$evenements key=key item=aEvenement}-->{
"id":"<!--{$aEvenement.id_evenement}-->",
"nom":"<!--{$aEvenement.nom}-->",
"dateDebut":"<!--{$aEvenement.dateDebut}-->",
"dateFin":"<!--{$aEvenement.dateFin}-->",
"heureDebut":"<!--{$aEvenement.heureDebut}-->",
"heureFin":"<!--{$aEvenement.heureFin}-->",
"jourEntier":"<!--{$aEvenement.jour_entier}-->",
"periodicite":"<!--{$aEvenement.periodicite}-->",
"uid":"<!--{$aEvenement.uid}-->",
"infoNom":"<!--{$aEvenement.infoContact.last_name}-->",
"infoPrenom":"<!--{$aEvenement.infoContact.first_name}-->",
"infoMail":"<!--{$aEvenement.infoContact.email}-->",
"infoTel":"<!--{$aEvenement.infoContact.tel}-->",
"nomLieu":"<!--{$aEvenement.lieuEvenement.nom}-->",
"communeLieu":"<!--{$aEvenement.lieuEvenement.commune}-->",
"latLieu":<!--{if $aEvenement.lieuEvenement.latitude!=""}--><!--{$aEvenement.lieuEvenement.latitude}--><!--{else}-->0<!--{/if}-->,
"longLieu":<!--{if $aEvenement.lieuEvenement.longitude!=""}--><!--{$aEvenement.lieuEvenement.longitude}--><!--{else}-->0<!--{/if}-->,
"rueLieu":"<!--{$aEvenement.rue}-->",
"npaLieu":"<!--{$aEvenement.npa}-->",
"calendrierId":"<!--{$aEvenement.calendrierEvenement.id_calendrier}-->",
"calendrierNom":"<!--{$aEvenement.calendrierEvenement.nom}-->",
"calendrierCouleur":"<!--{$aEvenement.calendrierEvenement.couleur}-->"
},<!--{/foreach}-->]}